feedback/fb_form/urls.py
from django.conf.urls import url

from . import views

app_name = 'fb_form'
urlpatterns = [
    url(r'^$', views.index, name='home'),
]

feedback/feedback/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^', include('fb_form.urls')),
    url(r'^admin/', admin.site.urls),
]

feedback/fb_form/models.py
from django.db import models

# Create your models here.

class fb_form(models.Model):
    c_name =models.CharField(max_length=30)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)
    outof=models.FloatField()

    def __str__(self):
        return self.c_name

feedback/fb_form/forms.py
from django import forms
from .models import fb_form

class fb_form_Form(forms.ModelForm):
    class Meta:
        model= fb_form
        exclude=[]

feedback/fb_form/views.py
from django.shortcuts import render
from .forms import fb_form_Form

def index(request):
    if request.method== 'POST':
        form = fb_form_Form(request.POST)

        if(form.is_valid()):
            form.save()

            return render(request,'fb_form/thanks.html')
        else:
            return render(request, 'fb_form/than.html')
    else:
        form= fb_form_Form()
    return render(request,'fb_form/fb_form.html',{'form':form})

feedback/templates/fb_form/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

feedback/templates/fb_form/fb_form.html
{% extends 'fb_form/base.html' %}
 
{% block title %}Feedback Form{% endblock %}
 
{% block body %}
    <h1>hellow</h1>
<form action="{% url 'fb_form:home' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
</form>
{% endblock %}

feedback/templates/fb_form/thanks.html
{% extends 'fb_form/base.html' %}
 
{% block title %}Thanks{% endblock %}
 
{% block body %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'form:home' %}">Response again?</a></p>
{% endblock %}